/**
 * farm/sprites.js — 데일리 농장 도트 (16×16 픽셀맵 → 픽셀마다 음영 계산 → 캔버스 → dataURL 캐시).
 * 픽셀맵은 글자 한 칸 = 픽셀 하나, '.'은 투명, o = 외곽선. 글자 색은 팔레트로 정한다.
 * 음영: 같은 재질(그룹)의 픽셀 덩어리마다 가장자리에서 얼마나 안쪽인지로 볼록한 높이를 만들고,
 * 왼쪽 위 빛을 받아 7단계 색(그늘은 푸른 보라 쪽, 빛은 따뜻한 쪽으로)에서 고른다. 외곽선은 맞닿은 색의 가장 어두운 색.
 * 작물 55종은 모양 틀 22개에 작물마다 색을, 요리 100개는 그릇 틀 16개에 재료 색을 입혀 만든다.
 * 이름: tile:* · grow:0~2 · char:0~2 · tab:* · cur:* · icon:* · seed:0~3 · item:* · crop:<id> · ready:<id> · dish:<번호>
 */
(function () {
  const root = typeof window !== 'undefined' ? window : globalThis;
  const F = (root.DailyFarm = root.DailyFarm || {});
  const D = F.data;

  const OUT = '#2b1d14';
  /** 등급 테두리 색: 일반 · 고급 · 희귀 · 전설 */
  const TIER_COLORS = ['#9e9e9e', '#43a047', '#1e88e5', '#fb8c00'];

  // ── 색 ──
  const hex2 = (h) => { const n = parseInt(h.slice(1), 16); return [n >> 16, (n >> 8) & 255, n & 255]; };
  const rgb2 = (c) => '#' + c.map((v) => Math.round(Math.min(255, Math.max(0, v))).toString(16).padStart(2, '0')).join('');
  /** a → b로 t만큼 */
  const lerp = (a, b, t) => { const x = hex2(a), y = hex2(b); return rgb2(x.map((v, i) => v + (y[i] - v) * t)); };
  /** t < 0이면 검정 쪽, t > 0이면 흰색 쪽으로 */
  const mix = (hex, t) => lerp(hex, t < 0 ? '#000000' : '#ffffff', Math.abs(t));
  const SHADOW_HUE = '#2e2650';
  const LIGHT_HUE = '#fff6d8';
  const RAMP = 7; // 0 가장 어두움 · 3 바탕색 · 6 가장 밝음
  const DITHER = [0.25, 0.75, 1, 0.5];
  const rampCache = {};
  /** 바탕색 하나 → 7단계 (그늘은 어둡게 + 푸른 보라, 빛은 밝게 + 따뜻하게) */
  function ramp(base) {
    if (!rampCache[base]) {
      const r = [];
      for (let i = 3; i >= 1; i--) r.push(lerp(mix(base, -0.11 * i), SHADOW_HUE, 0.06 * i));
      r.push(base);
      for (let i = 1; i <= 3; i++) r.push(lerp(base, LIGHT_HUE, 0.19 * i));
      rampCache[base] = r;
    }
    return rampCache[base];
  }
  /** 그룹 안에서 밝기 힌트로 쓰는 글자: 글자 → [바탕 글자, 단계 ±] */
  const HINT = { b: ['a', -1], c: ['a', 1], e: ['d', -1], l: ['d', 1], q: ['p', -1], r: ['p', 1], x: ['w', -1], h: ['g', -1] };
  const rows = (s) => s.trim().split('\n').map((r) => r.trim());

  // ── 작물 틀 (a 몸통 · b 그늘 · c 빛 · d 잎 · e 잎 그늘 · f/g 무늬) ──
  const CROP_T = {
    round: rows(`
      ................
      .......oo.......
      ......odeo......
      ....oodddeoo....
      ...oaadeeaabo...
      ..oacaaaaaaabo..
      .oacaaaaaaaabbo.
      .oacaaaaaaaabbo.
      .oaaaaaaaaaabbo.
      .oaaaaaaaaaabbo.
      .oaaaaaaaaabbbo.
      ..oaaaaaaabbbo..
      ..obaaaaabbbbo..
      ...oobbbbbboo...
      .....oooooo.....
      ................`),
    bulb: rows(`
      ................
      .......od.......
      .......de.......
      ......oddo......
      ......oaao......
      .....oacabo.....
      ....oacaaabo....
      ...oacaaaaabo...
      ..oacaaaaaaabo..
      ..oaaafaaafabo..
      ..oaaafaaafabo..
      ...oaaaaaaabo...
      ....obbbbbbo....
      .....oooooo.....
      ......f..f......
      .....f..f..f....`),
    root: rows(`
      ................
      .....d..d.......
      .....de.de.d....
      ......ddedde....
      .......dde......
      .....oooooo.....
      ....oacaaabo....
      ....oacaaabo....
      ....oaafaabo....
      .....oaaabo.....
      .....oacabo.....
      .....oafabo.....
      ......oaao......
      ......oabo......
      .......oo.......
      ................`),
    tuber: rows(`
      ................
      ................
      ................
      ......ooooo.....
      ....ooaaaaaoo...
      ...oacaaafaaao..
      ..oacaaaaaaaabo.
      .oacaafaaaaaabo.
      .oaaaaaaaaafabo.
      .oaaaaaaaaaaabo.
      ..oaaafaaaaabbo.
      ..obaaaaaaabbo..
      ...oobbbbbbbo...
      .....ooooooo....
      ................
      ................`),
    leafy: rows(`
      ................
      ................
      ......oooo......
      ....ooldddoo....
      ...olddeddddo...
      ..oldddeddeddo..
      ..odlddedddedo..
      .oldddeddddedeo.
      .odddedddeddeeo.
      .oddeddddedddeo.
      .odddddeddddeeo.
      ..oeddddddddeo..
      ..oeeddddddeeo..
      ...ooeeeeeeoo...
      .....oooooo.....
      ................`),
    long: rows(`
      ................
      ...........dd...
      ..........odde..
      .........oaaeo..
      ........oacabo..
      .......oacaabo..
      ......oacaabo...
      .....oacaabo....
      ....oacafbo.....
      ...oacaabo......
      ..oacaabo.......
      ..oaaabo........
      ..oaabo.........
      ...obo..........
      ....o...........
      ................`),
    stalk: rows(`
      ................
      .....d...d......
      .....d.d.d.d....
      .....d.d.de.d...
      .....dede.e.d...
      ......dde.ee....
      ......ddeee.....
      ......ddeee.....
      ......oddeo.....
      ......offfo.....
      ......oacao.....
      ......oacao.....
      ......oacao.....
      ......oaabo.....
      ......g.g.g.....
      ................`),
    grain: rows(`
      ................
      ........a.......
      .....a.aba..a...
      ....aba.ba.aba..
      ....ab.aba.ab...
      ...aba.ab.aba...
      ...ab.aba.ab....
      ....b.ab..b.....
      .....d.d.d......
      .....d.d.d......
      ......ddd.......
      ......ofo.......
      .......d........
      ......d.d.......
      .....d...d......
      ................`),
    corn: rows(`
      ................
      .........oo.....
      ........oafo....
      .......oafgfo...
      ......oagfaao...
      .....doafagfo...
      ....ddoagafao...
      ...ddeofgafo....
      ...deeoafgao....
      ..ddeooagfo.....
      ..deeeoafo.d....
      .ddeeeooo.dd....
      .deeeeeeddde....
      ..eeeeeeeee.....
      ...eeeeeee......
      ................`),
    cluster: rows(`
      ................
      ........d.dd....
      .......ddde.....
      ....oooooeooo...
      ...ocabcabcabo..
      ...oabbabbabbo..
      ...obcabcabcbo..
      ....oabbabbbo...
      ....obcabcabo...
      .....oabbabo....
      .....obcabbo....
      ......oabbo.....
      ......obbbo.....
      .......obo......
      ........o.......
      ................`),
    berry: rows(`
      ................
      ................
      ......d.de......
      ....oddeedeo....
      ...oadeddedao...
      ..oacafaafaabo..
      ..ocaaaaaaafbo..
      ..oaafaafaaabo..
      ...oaaaafaabo...
      ...ofaaaaafbo...
      ....oaafaabo....
      ....oaaaabbo....
      .....oafabo.....
      ......oabo......
      .......oo.......
      ................`),
    cherry: rows(`
      ................
      ........ddd.....
      .......gdde.....
      ......g.g.......
      .....g...g......
      ....g.....g.....
      ....g......g....
      ...g.......g....
      ..oooo....oooo..
      .oacaao..oacaao.
      .oaaabo..oaaabo.
      .oaaabo..oaaabo.
      .obbbbo..obbbbo.
      ..oooo....oooo..
      ................
      ................`),
    melon: rows(`
      ................
      ................
      .......od.......
      .....oooooo.....
      ...ooafaafaoo...
      ..oacfaafaafbo..
      .oacafaafaafabo.
      .oaafaafaafabbo.
      .oaafaafaafabbo.
      .oaafaafaafabbo.
      .oaafaafaafbbbo.
      ..oafaafaafbbo..
      ...oofaafaboo...
      .....oooooo.....
      ................
      ................`),
    pumpkin: rows(`
      ................
      ................
      .......de.......
      .......d........
      ....oooooooo....
      ..ooacabaacboo..
      .oacaabaaabaabo.
      .oacaabaaabaabo.
      .oaaaabaaabaabo.
      .oaaaabaaabaabo.
      .oaaaabaaababbo.
      ..oaaabaaabbbo..
      ...oobbbbbboo...
      .....oooooo.....
      ................
      ................`),
    mushroom: rows(`
      ................
      ................
      .....oooooo.....
      ...ooaccaaaoo...
      ..oacaaafaaabo..
      .oacafaaaaafabo.
      .oaaaaaafaaabbo.
      .obbbbbbbbbbbbo.
      ..ooooggggoooo..
      ......ogggo.....
      ......oggho.....
      ......oggho.....
      .....ogggho.....
      .....ooooooo....
      ................
      ................`),
    pod: rows(`
      ................
      ............d...
      ...........dd...
      ..........oao...
      .........oafbo..
      ........oaffbo..
      .......oafabo...
      ......oaffbo....
      .....oafabo.....
      ....oaffbo......
      ...oafabo.......
      ..oaffbo........
      ..oaabo.........
      ...oo...........
      ................
      ................`),
    pineapple: rows(`
      .......d........
      ....d..dd..d....
      .....d.de.d.....
      ......ddedd.....
      .......de.......
      .....oooooo.....
      ....ofacfabo....
      ...oacfacfabo...
      ...ofacfacfbo...
      ...oacfacfabo...
      ...ofacfacfbo...
      ...oacfacfabo...
      ....ofacfabo....
      .....oooooo.....
      ................
      ................`),
    bell: rows(`
      ................
      ........d.......
      .......dd.......
      ....ooodooo.....
      ...oacaoaaabo...
      ..oacaaoaaaabo..
      ..oacaaaaaaabo..
      ..oaaaaaaaaabo..
      ..oaaaaaaaaabo..
      ..oaaaaaaaabbo..
      ..oaaaaaaaabbo..
      ...oaaobaabbo...
      ....oobooboo....
      ......o..o......
      ................
      ................`),
    tree: rows(`
      ................
      ................
      .....oooooo.....
      ...oodlddldoo...
      ..odlddeddlddo..
      .odldedddeddldo.
      .oddddeddddeddo.
      .oeddeddeddeeeo.
      ..oeeeoaaoeeeo..
      ...ooo.oao.oo...
      .......oao......
      ......oalao.....
      ......oaaao.....
      ......oaabo.....
      ......ooooo.....
      ................`),
    pear: rows(`
      ................
      .......dd.......
      .......od.......
      ......oaao......
      .....oacabo.....
      .....oacabo.....
      ....oacaaabo....
      ...oacaaaaabo...
      ..oacaaaaaaabo..
      ..oaaaaaaaaabo..
      ..oaaaaaaaabbo..
      ..oaaaaaaabbbo..
      ...oaaaabbbbo...
      ....oobbbboo....
      ......oooo......
      ................`),
    flower: rows(`
      ................
      ......f...f.....
      .......f.f......
      ...oo..ff..oo...
      ..oaao.ff.oaao..
      ..oacaoffoacao..
      ..oaacaffaacbo..
      ...oaaaaaaabo...
      ...oaacaaaabo...
      ....oaaaaabo....
      .....obbbbo.....
      ......oddo......
      .......d........
      ......dd.e......
      .....de..ee.....
      ................`),
    slice: rows(`
      ................
      ................
      .....oooooo.....
      ...ooaaaaaaoo...
      ..oaaffffffaao..
      ..oafkfffkffao..
      .oaffffccfffkao.
      .oafkfccccfffao.
      .oafffccccfkfao.
      .oakfffccffffao.
      ..oafffkfffkao..
      ..oaaffffffaao..
      ...ooaaaaaaoo...
      .....oooooo.....
      ................
      ................`),
  };
  /** 틀마다 음영을 같이 계산할 글자 묶음 (기본: 몸통+무늬 · 잎) */
  const CROP_GROUPS = { default: ['abcf', 'del'], slice: ['a', 'fc'], corn: ['afg', 'del'], mushroom: ['abcf', 'gh', 'del'] };
  /** 손으로 찍은 빛 · 그늘 힌트를 몇 단계로 셀지 (알이 여러 개인 송이 · 골이 있는 호박은 힌트가 모양을 만든다) */
  const CROP_HINT_K = { cluster: 2, pumpkin: 2 };

  /** 작물 → [틀, 팔레트] */
  const LEAF = '#5aa845';
  const CROP_ART = {
    potato: ['tuber', { a: '#c8a165', f: '#8a6a3b' }],
    sweetpotato: ['tuber', { a: '#b8506e', f: '#6e2440' }],
    carrot: ['root', { a: '#f08a2c', f: '#c76516', d: LEAF }],
    radish: ['root', { a: '#ecebdf', f: '#d1cdb6', d: '#6fbf4f' }],
    onion: ['bulb', { a: '#d9a05b', f: '#a8743a', d: '#7cb84f' }],
    scallion: ['stalk', { a: '#eeebd8', d: '#4caf50', f: '#d0a050', g: '#e8e0c8' }],
    garlic: ['bulb', { a: '#ece6d6', f: '#bdb39a', d: '#9bbf6a' }],
    napa: ['leafy', { d: '#c4dd80' }],
    cabbage: ['leafy', { d: '#9ccc65' }],
    lettuce: ['leafy', { d: '#72bd3e' }],
    spinach: ['leafy', { d: '#3a8a35' }],
    cucumber: ['long', { a: '#3f8f3a', f: '#a5d68f', d: '#f2d14c' }],
    zucchini: ['long', { a: '#6bae4a', f: '#c3e2a8', d: '#3d7a2a' }],
    eggplant: ['long', { a: '#6b3a8c', f: '#9a64bf', d: LEAF }],
    tomato: ['round', { a: '#e53935', d: LEAF }],
    chili: ['long', { a: '#d32f2f', f: '#ff8a80', d: LEAF }],
    corn: ['corn', { a: '#ffd54f', f: '#ffca28', g: '#ffe57a', d: '#8bc34a' }],
    rice: ['grain', { a: '#e8d48a', d: '#8bb84a', f: '#c0a060' }],
    wheat: ['grain', { a: '#e0b04a', d: '#c9a24a', f: '#9a7a30' }],
    soy: ['pod', { a: '#9ccc65', f: '#e6ee9c', d: LEAF }],
    strawberry: ['berry', { a: '#e53935', f: '#fff176', d: LEAF }],
    watermelon: ['melon', { a: '#43a047', f: '#1b5e20', d: '#6d4c41' }],
    melon: ['melon', { a: '#b5d36b', f: '#eef3cf', d: '#6d4c41' }],
    orientalmelon: ['melon', { a: '#ffd600', f: '#fffde7', d: '#6d8f3a' }],
    grape: ['cluster', { a: '#7b3fa0', d: '#6aa84f' }],
    blueberry: ['cluster', { a: '#3f51b5', d: LEAF }],
    cherry: ['cherry', { a: '#c62828', g: '#6d4c41', d: LEAF }],
    peach: ['round', { a: '#ffab91', d: '#66bb6a' }],
    kiwi: ['slice', { a: '#7a5a32', f: '#8bc34a', c: '#eef6c4', k: '#2b1d14' }],
    pineapple: ['pineapple', { a: '#f9a825', f: '#b97a10', d: '#4caf50' }],
    mango: ['pear', { a: '#ffb300', d: '#66bb6a' }],
    avocado: ['pear', { a: '#558b2f', d: '#6d4c41' }],
    asparagus: ['stalk', { a: '#8bc34a', d: '#7a9a3a', f: '#a0522d', g: '#c5e1a5' }],
    broccoli: ['tree', { d: '#43a047', a: '#9ccc65' }],
    paprika: ['bell', { a: '#f4511e', d: '#43a047' }],
    kabocha: ['pumpkin', { a: '#3d6b35', d: '#6d4c41' }],
    shiitake: ['mushroom', { a: '#8d5a3b', f: '#c99a72', g: '#f0e0c8' }],
    ginger: ['tuber', { a: '#e0b46b', f: '#a07a3a' }],
    sesame: ['pod', { a: '#b5a374', f: '#f5ecd0', d: '#7a9a3a' }],
    peanut: ['tuber', { a: '#d7b98a', f: '#a0805a' }],
    ginseng: ['root', { a: '#e8d2a0', f: '#c4a46a', d: '#4caf50' }],
    matsutake: ['mushroom', { a: '#a0703f', f: '#7a4f28', g: '#f2e6cf' }],
    truffle: ['tuber', { a: '#4a3a2c', f: '#2a1f16' }],
    saffron: ['flower', { a: '#9575cd', f: '#e53935', d: LEAF }],
    vanilla: ['pod', { a: '#5d4037', f: '#8d6e63', d: LEAF }],
    cacao: ['pear', { a: '#d1801f', d: '#5d8f2a' }],
    coffee: ['cluster', { a: '#c62828', d: '#43a047' }],
    wasabi: ['root', { a: '#9ccc65', f: '#6b9b37', d: '#388e3c' }],
    shinemuscat: ['cluster', { a: '#c5e17a', d: '#6aa84f' }],
    dragonfruit: ['slice', { a: '#e91e63', f: '#f6f0f2', c: '#ffffff', k: '#212121' }],
    goldapple: ['round', { a: '#ffd54f', d: '#66bb6a' }],
    moonpeach: ['round', { a: '#dfe4ff', d: '#90a4ae' }],
    starshroom: ['mushroom', { a: '#5c6bc0', f: '#fff59d', g: '#e8eaf6' }],
    rainbowcorn: ['corn', { a: '#e53935', f: '#43a047', g: '#1e88e5', d: '#8bc34a' }],
    flamechili: ['long', { a: '#ff6d00', f: '#ffeb3b', d: '#d32f2f' }],
  };

  // ── 요리 틀 (p 주재료 · q 그늘 · r 빛 · s · t 다른 재료 · w 그릇 · x 그릇 그늘) ──
  const DISH_T = {
    bowl: rows(`
      ................
      ................
      ......v...v.....
      .......v...v....
      ......v...v.....
      ................
      ..oooooooooooo..
      .opprppsppptppo.
      .oqpppspptpppqo.
      .owwwwwwwwwwwxo.
      ..owwwwwwwwwxo..
      ...owwwwwwwxo...
      ....owwwwwxo....
      .....oxxxxo.....
      ......oooo......
      ................`),
    noodle: rows(`
      ................
      ............z...
      ...........z.z..
      ..........z.z...
      .........z.z....
      ........z.z.....
      ..oooooooooooo..
      .opnnpnnspnntqo.
      .onnpnnnnnpnnno.
      .owwwwwwwwwwwxo.
      ..owwwwwwwwwxo..
      ...owwwwwwwxo...
      ....owwwwwxo....
      .....oxxxxo.....
      ......oooo......
      ................`),
    rice: rows(`
      ................
      ................
      ................
      ......oooo......
      ....oorpprro....
      ...orpppsppro...
      ..oppsppptpppo..
      .oqppppppppppqo.
      .oxxxxxxxxxxxxo.
      .owwwwwwwwwwwxo.
      ..owwwwwwwwwxo..
      ...owwwwwwwxo...
      ....owwwwwxo....
      .....oxxxxo.....
      ......oooo......
      ................`),
    plate: rows(`
      ................
      ................
      ................
      ................
      ................
      ......oooo......
      ....oorpspoo....
      ...opsppptppo...
      ..opppspppsqqo..
      ..oqpptpppqqqo..
      owwwwwwwwwwwwwwo
      oxwwwwwwwwwwwwxo
      .oxxxxxxxxxxxxo.
      ..oooooooooooo..
      ................
      ................`),
    pancake: rows(`
      ................
      ................
      ................
      ................
      ................
      ................
      ....oooooooo....
      ..oorpppsppqoo..
      .orppsppptppqqo.
      .oqpppppsppqqqo.
      owwoooooooooowwo
      oxwwwwwwwwwwwwxo
      .oxxxxxxxxxxxxo.
      ..oooooooooooo..
      ................
      ................`),
    drink: rows(`
      ................
      ..........zz....
      .........z......
      ...ooooooozooo..
      ...ogppppzpgo...
      ...ogrpppzpgo...
      ...ogpppppqgo...
      ....ogpppqgo....
      ....ogpppqgo....
      ....ogppqqgo....
      ....ogpqqqgo....
      ....oggggggo....
      .....oooooo.....
      ................
      ................
      ................`),
    tea: rows(`
      ................
      ................
      ......v..v......
      .......v..v.....
      ......v..v......
      ................
      ...oooooooooo...
      ...orpppppqqo...
      ...owwwwwwwxooo.
      ...owwwwwwwxo.o.
      ...owwwwwwwxooo.
      ....owwwwwxo....
      ..oooooooooooo..
      .oxwwwwwwwwwwxo.
      ..oooooooooooo..
      ................`),
    bread: rows(`
      ................
      ................
      ................
      ................
      ................
      ....oooooooo....
      ..oorppppppqoo..
      .orpppsppsppqqo.
      .opppqpppqppqqo.
      .oppsppppsppqqo.
      .oqpppppppppqqo.
      .oqqqqqqqqqqqqo.
      ..oooooooooooo..
      ................
      ................
      ................`),
    cake: rows(`
      ................
      ................
      ................
      ....s...s...s...
      ..oooooooooooo..
      ..owwwwwwwwwwo..
      ..opppppppppqo..
      ..osssssssssto..
      ..opppppppppqo..
      ..owwwwwwwwwxo..
      ..opppppppppqo..
      ..oqqqqqqqqqqo..
      ..oooooooooooo..
      ................
      ................
      ................`),
    pie: rows(`
      ................
      ................
      ................
      ................
      ................
      ................
      ..oooooooooooo..
      .ozszszszszszzo.
      .ozzzzzzzzzzzzo.
      .ozszszszszszzo.
      oxzzzzzzzzzzzzxo
      .oxxxxxxxxxxxxo.
      ..oooooooooooo..
      ................
      ................
      ................`),
    jar: rows(`
      ................
      ................
      .....oooooo.....
      .....oyyyyo.....
      ....oooooooo....
      ....oggggggo....
      ...ogpppppppo...
      ...ogrpppppqo...
      ...ogpwwwwpqo...
      ...ogpwwwwpqo...
      ...ogpppppqqo...
      ...ogpppppqqo...
      ...oggggggggo...
      ....oooooooo....
      ................
      ................`),
    cookie: rows(`
      ................
      ................
      ................
      ................
      ......oooo......
      .....oprspo.....
      .....opsppo.....
      .....oqqqqo.....
      ..oooooooooooo..
      .oppspo..oppspo.
      .opsppo..opsppo.
      .oqqqqo..oqqqqo.
      ..oooo....oooo..
      ................
      ................
      ................`),
    choco: rows(`
      ................
      ................
      ................
      ................
      ..ooooooooooooo.
      ..orpqorpqorpqo.
      ..opqqopqqopqqo.
      ..ooooooooooooo.
      ..orpqorpqorpqo.
      ..opqqopqqopqqo.
      ..ooooooooooooo.
      ..owwwwwwwwwwwo.
      ..ossssssssssxo.
      ..ooooooooooooo.
      ................
      ................`),
    skewer: rows(`
      ................
      ......oooo......
      .....orrpqo.....
      .....opppqo.....
      ......oooo......
      ......oooo......
      .....orssto.....
      .....osssto.....
      ......oooo......
      ......oooo......
      .....orrpqo.....
      .....opppqo.....
      ......oooo......
      .......zz.......
      .......zz.......
      .......zz.......`),
    ice: rows(`
      ................
      ................
      .......oo.......
      .....oowwoo.....
      ....owwwwwwo....
      ...owwpwwwpwo...
      ..owwppwwpppwo..
      ..owpppwwppswo..
      .oooooooooooooo.
      .owwwwwwwwwwwxo.
      ..owwwwwwwwwxo..
      ...owwwwwwwxo...
      ....owwwwwxo....
      .....oxxxxo.....
      ......oooo......
      ................`),
    icecream: rows(`
      ................
      ......oooo......
      .....orppqo.....
      ....orpppsqo....
      ....opsppqqo....
      ....oqqqqqqo....
      .....ozzzzo.....
      .....ozxzzo.....
      ......ozzo......
      ......oxzo......
      .......oo.......
      ................
      ................
      ................
      ................
      ................`),
  };
  const DISH_GROUPS = ['pqrst', 'wx', 'z', 'y'];
  const DISH_FIXED = { w: '#f4f1ea', v: '#c9d3d8', z: '#8d6e63', g: '#d6eef8', y: '#c0392b', n: '#f3e2b3' };
  const DISH_FIXED_BY_T = { pie: { z: '#d9a45b' }, icecream: { z: '#e0b46b' }, cake: { w: '#fff8ee' } };
  /** 요리 이름 → 틀 (앞에서부터 먼저 맞는 것) */
  const DISH_RULES = [
    [/주스|스무디|넥타/, 'drink'], [/차$|커피|모카/, 'tea'], [/빙수/, 'ice'], [/아이스크림/, 'icecream'],
    [/국수|칼국수|소바|파스타/, 'noodle'], [/수프|국$|찌개|스튜|죽$|전골|냉국|화채|카레/, 'bowl'],
    [/밥|리조또|빠에야/, 'rice'], [/전$|부침|파전/, 'pancake'], [/빵|토스트|머핀/, 'bread'],
    [/케이크/, 'cake'], [/파이|타르트/, 'pie'], [/잼|통조림|정과/, 'jar'], [/초콜릿/, 'choco'],
    [/쿠키|강정|맛탕|인절미|팝콘/, 'cookie'], [/탕후루/, 'skewer'],
  ];
  const STAPLES = ['rice', 'wheat'];
  const BASE_TEMPLATES = ['rice', 'bread', 'cake', 'pie', 'cookie', 'pancake'];
  /** 요리하면 작물 겉모습과 색이 달라지는 재료 (커피 열매 → 커피, 수박 껍질 → 과육 등) */
  const FOOD_COLOR = {
    coffee: '#5d4037', cacao: '#5d3a1a', soy: '#d9c48f', vanilla: '#f3e5c0', kiwi: '#8bc34a',
    watermelon: '#ef5350', kabocha: '#f2b134', sweetpotato: '#e0a040', wheat: '#e0b04a', rice: '#f2ede0',
  };
  const cropColor = (id) => FOOD_COLOR[id] || CROP_ART[id][1].a || CROP_ART[id][1].d;
  function dishArt(dish) {
    const t = (DISH_RULES.find(([re]) => re.test(dish.name)) || [null, 'plate'])[1];
    const ids = dish.ings.map(([id]) => id);
    const staple = ids.find((id) => STAPLES.includes(id));
    const others = ids.filter((id) => !STAPLES.includes(id));
    // 밥 · 빵 · 반죽이 바탕인 틀은 바탕이 주재료, 나머지는 바탕이 아닌 재료가 주재료
    const order = BASE_TEMPLATES.includes(t) && staple ? [staple, ...others] : [...others, ...ids.filter((id) => STAPLES.includes(id))];
    const [p, s = p, u = s] = order.map(cropColor);
    return [t, { ...DISH_FIXED, ...(DISH_FIXED_BY_T[t] || {}), p, s, t: u }];
  }

  // ── 그 밖의 도트 [픽셀맵, 팔레트, 음영 그룹] ──
  const CHAR_PAL = { h: '#f2c94c', g: '#c0392b', s: '#f5c9a0', k: '#2b1d14', c: '#e57373', b: '#3f6fb5', z: '#6d4c41' };
  const CHAR_G = ['s', 'c', 'b', 'z'];
  const MISC = {
    'tile:soil': [`
      aaaaaaaaaaaaaaaa
      aabaaaaaacaaaaba
      aaaaacaaaaaabaaa
      abaaaaaabaaaaaac
      aaaacaaaaaacaaaa
      aaaaaaabaaaaaaaa
      acaaaaaaaaabaaba
      aaaabaaacaaaaaaa
      aaaaaaaaaaaacaaa
      abaacaaaabaaaaaa
      aaaaaaaaaaaaabaa
      aacaaabaaacaaaaa
      aaaaaaaaaaaaaaca
      abaaaacaabaaaaaa
      aaaaaaaaaaaabaaa
      aacaabaaaaaaaaaa`, { a: '#8b5a2b', b: '#6f4520', c: '#a8733f' }, []],
    'tile:tilled': [`
      cccccccccccccccc
      aaaaaaaaaaaaaaaa
      abaaaaaabaaaaaba
      bbbbbbbbbbbbbbbb
      cccccccccccccccc
      aaaaaaaaaaaaaaaa
      aaaabaaaaaabaaaa
      bbbbbbbbbbbbbbbb
      cccccccccccccccc
      aaaaaaaaaaaaaaaa
      abaaaaaabaaaaaba
      bbbbbbbbbbbbbbbb
      cccccccccccccccc
      aaaaaaaaaaaaaaaa
      aaaabaaaaaabaaaa
      bbbbbbbbbbbbbbbb`, { a: '#7a4a22', b: '#5a3516', c: '#9c6834' }, []],
    'tile:locked': [`
      aaaaaaaaaaaaaaaa
      aacaaaaabaaaaaca
      acbcaaaaaaaacaaa
      aaaaaabaaaacbcaa
      aaaaaaaaaaaaaaaa
      abaaaacaaaaaaaba
      aaaaacbcaaabaaaa
      aaaaaaaaaaaaaaaa
      aacaaaaaabaaaaaa
      acbcaaaaaaaaacaa
      aaaaaabaaaaacbca
      aaaaaaaaaaaaaaaa
      abaaaaaacaaaaaaa
      aaaaacaacbcaabaa
      aaaacbcaaaaaaaaa
      aaaaaaaaaaaaaaaa`, { a: '#6a9a4a', b: '#4e7a36', c: '#8cbc6a' }, []],
    'grow:0': [`
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      ................
      .......oo.......
      ......oyyo......
      ......oyyo......
      ....ooxooxoo....
      ...oxxxxxxxxo...
      ................`, { y: '#d9b57a', x: '#5a3516' }, ['y']],
    'grow:1': [`
      ................
      ................
      ................
      ................
      ................
      ................
      ...oo......oo...
      ..oddo....oddo..
      ..odddo..odddo..
      ...oedeooedeo...
      ....oeedeeo.....
      ......oddo......
      ......odeo......
      ......odeo......
      .....oxxxxo.....
      ................`, { d: '#6fbf4f', x: '#5a3516' }, ['de']],
    'grow:2': [`
      ................
      ................
      .......oo.......
      ......oddo......
      ..oo..odeo..oo..
      .oddo.odeo.oddo.
      .odddoodeoodddo.
      ..oeddodeoddeo..
      ...oeedddeeeo...
      ....ooddeeoo....
      ..oo..odeo..oo..
      .oddo.odeo.oddo.
      ..oedooddoodeo..
      ...ooeedeeoo....
      .....oxxxxo.....
      ................`, { d: '#5aae45', x: '#5a3516' }, ['de']],
    'char:0': [`
      ................
      ......oooo......
      .....ohhhho.....
      ...oohhhhhhoo...
      ..ohhhggghhhho..
      ...oossssssoo...
      ....osksskso....
      ....osssssso....
      .....oooooo.....
      ....ocbbbbco....
      ...oscbbbbcso...
      ....oobbbboo....
      .....obbbbo.....
      .....ob..bo.....
      .....oz..zo.....
      .....oo..oo.....`, CHAR_PAL, CHAR_G],
    'char:1': [`
      ................
      ......oooo......
      .....ohhhho.....
      ...oohhhhhhoo...
      ..ohhhggghhhho..
      ...oossssssoo...
      ....osksskso....
      ....osssssso....
      .....oooooo.....
      ....ocbbbbco....
      ...oscbbbbcso...
      ....oobbbboo....
      .....obbbbo.....
      ....obo..bo.....
      ....ozo..zo.....
      ....oo...oo.....`, CHAR_PAL, CHAR_G],
    'char:2': [`
      ................
      ......oooo......
      .....ohhhho.....
      ...oohhhhhhoo...
      ..ohhhggghhhho..
      ...oossssssoo...
      ....osksskso....
      ....osssssso....
      .....oooooo.....
      ....ocbbbbco....
      ...oscbbbbcso...
      ....oobbbboo....
      .....obbbbo.....
      .....ob..obo....
      .....oz..ozo....
      .....oo...oo....`, CHAR_PAL, CHAR_G],
    'tab:farm': [`
      ................
      .......oo.......
      .....oorroo.....
      ...oorrrrrroo...
      .oorrrrrrrrrroo.
      oooooooooooooooo
      .orrrrrrrrrrrro.
      .orwwrrrrrrwwro.
      .orwwrrrrrrwwro.
      .orrrrowworrrro.
      .orrrrowworrrro.
      .orrrrowworrrro.
      .oooooooooooooo.
      gggggggggggggggg
      ................
      ................`, { r: '#c0392b', w: '#f5f0e6', g: '#6a9a4a' }, ['r']],
    'tab:explore': [`
      ................
      ................
      ..oooooooooooo..
      ..owwwwwwwwwwo..
      ..owgwwwkwwwwo..
      ..owggwwwkwwwo..
      ..owwgwwwwkwwo..
      ..owwwwwwwwkwo..
      ..owwkwwwwwwwo..
      ..owwwkwwrwrwo..
      ..owwwwkwwrwwo..
      ..owwwwwwrwrwo..
      ..owwwwwwwwwwo..
      ..oooooooooooo..
      ................
      ................`, { w: '#f3e3b8', g: '#6a9a4a', k: '#8d6e63', r: '#d32f2f' }, ['w']],
    'tab:craft': [`
      ................
      ................
      ..ooooooooooo...
      ..ommmmmmmmmo...
      ..ommmmmmmmmo...
      ..ooooozzoooo...
      ......ozzo......
      ......ozzo......
      ......ozzo......
      ......ozzo......
      ......ozzo......
      ......ozzo......
      ......oyyo......
      ......oyyo......
      ......oooo......
      ................`, { m: '#b0bec5', z: '#a1887f', y: '#6d4c41' }, ['m', 'zy']],
    'tab:cook': [`
      ................
      ....v..v..v.....
      .....v..v..v....
      ....v..v..v.....
      ................
      ..oooooooooooo..
      ooommmmmmmmmmooo
      o.ommmmmmmmmmo.o
      ooommmmmmmmmmooo
      ..ommmmmmmmmmo..
      ..ommmmmmmmmmo..
      ..ommmmmmmmmmo..
      ...ommmmmmmmo...
      ....oooooooo....
      ................
      ................`, { m: '#90a4ae', v: '#b0bec5' }, ['m']],
    'tab:codex': [`
      ................
      ................
      ..oooooooooooo..
      ..obbbbbbbbbbo..
      ..obbbyyyybbbo..
      ..obbbyyyybbbo..
      ..obbbbbbbbbbo..
      ..obbbbybbbbbo..
      ..obbbyyybbbbo..
      ..obbbbybbbbbo..
      ..obbbbbbbbbbo..
      ..owwwwwwwwwwo..
      ..oxxxxxxxxxxo..
      ..oooooooooooo..
      ................
      ................`, { b: '#5c6bc0', y: '#ffd54f', w: '#fafafa' }, ['b', 'wx']],
    'tab:shop': [`
      ................
      ................
      ..oooooooooooo..
      .orrwwrrwwrrwwo.
      .orrwwrrwwrrwwo.
      oooooooooooooooo
      ..o.........o...
      ..o.........o...
      ..o..s.t.s..o...
      ..o.sssssss.o...
      ..oooooooooooo..
      ..ozzzzzzzzzzo..
      ..ozzzzzzzzzzo..
      ..oooooooooooo..
      ................
      ................`, { r: '#e53935', w: '#fafafa', s: '#ffb74d', t: '#81c784', z: '#a1887f' }, ['rw', 'st', 'z']],
    'icon:bag': [`
      ................
      ......oooo......
      .....o....o.....
      ....oooooooo....
      ...ozzzzzzzzo...
      ..ozzyzzzzyzzo..
      ..ozzzzzzzzzzo..
      ..ozooooooooxo..
      ..ozozzzzzzoxo..
      ..ozozzyyzzoxo..
      ..ozooooooooxo..
      ..ozzzzzzzzzxo..
      ..oxxxxxxxxxxo..
      ...oooooooooo...
      ................
      ................`, { z: '#c08a52', x: '#8d5f32', y: '#f2c94c' }, ['zx', 'y']],
    'icon:lock': [`
      ................
      ................
      ................
      ......oooo......
      .....o....o.....
      .....o....o.....
      ....oooooooo....
      ....oyyyyyyo....
      ....oyyooyyo....
      ....oyyooyyo....
      ....oyyyyyyo....
      ....oooooooo....
      ................
      ................
      ................
      ................`, { y: '#ffca28' }, ['y']],
    'icon:boost': [`
      ................
      .........oooo...
      ........oyyyo...
      .......oyyyo....
      ......oyyyo.....
      .....oyyyoooo...
      ....oyyyyyyyo...
      ....ooooyyyo....
      .......oyyo.....
      ......oyyo......
      .....oyyo.......
      ....oyyo........
      ....oyo.........
      ....oo..........
      ................
      ................`, { y: '#ffd54f' }, ['y']],
    'seed': [`
      ................
      ...oooooooooo...
      ...owwwwwwwwo...
      ...oxxxxxxxxo...
      ...oaaaaaaaao...
      ...oaadaadaao...
      ...oaaddddaao...
      ...oaaaddaaao...
      ...oaaaddaaao...
      ...oaafffaaao...
      ...oaaaaaaaao...
      ...obbbbbbbbo...
      ...oooooooooo...
      ................
      ................
      ................`, { w: '#fafafa', d: '#4caf50', f: '#8d6e63' }, ['abf', 'wx']],
    'item:mat': [`
      ................
      ................
      ................
      ................
      ..oooooooooooo..
      ..ozzzzzzzzzzo..
      ..ozzzzzzzzzzo..
      ..oooooooooooo..
      ..ozzzzzzzzzzo..
      ..ozzzzzzzzzzo..
      ..oooooooooooo..
      ..ozzzzzzzzzzo..
      ..ozzzzzzzzzzo..
      ..oooooooooooo..
      ................
      ................`, { z: '#c99a64' }, ['z']],
    'item:mat2': [`
      ................
      ................
      .....oooooo.....
      ....occaaabo....
      ...ocaaaaaabo...
      ..oooooooooooo..
      ...oaaaaaabbo...
      ....oaaaabbo....
      .....oaabbo.....
      ......oabo......
      .......oo.......
      ................
      ................
      ................
      ................
      ................`, { a: '#4fc3f7' }, ['abc']],
    'item:gear': [`
      ................
      ................
      ......oooo......
      .....occaao.....
      .....oaaabo.....
      ......oooo......
      ....oooooooo....
      ...oyyyyyyyyo...
      ..oyyoooooozyo..
      ..oyo......oyo..
      ..oyo......ozo..
      ..ozyoooooozzo..
      ...ozzzzzzzzo...
      ....oooooooo....
      ................
      ................`, { a: '#e91e63', y: '#ffd54f', z: '#f9a825' }, ['abc', 'yz']],
    // 장신구 모습 1~9 (0은 item:gear 반지). 효과와 상관없이 얻을 때 무작위 (GEAR.looks)
    // 목걸이
    'gear:1': [`
      ................
      .oo..........oo.
      .oyo........oyo.
      ..oyo......oyo..
      ...oyo....oyo...
      ....oyo..oyo....
      .....oyooyo.....
      ......oyyo......
      .....oooooo.....
      ....oaacaaao....
      ....oaaaaabo....
      .....oaaabo.....
      ......oabo......
      .......oo.......
      ................
      ................`, { y: '#ffd54f', a: '#e53935' }, ['y', 'abc']],
    // 귀걸이
    'gear:2': [`
      ................
      ................
      ...o........o...
      ..oyo......oyo..
      ...o........o...
      ...o........o...
      ...o........o...
      ..oco......oco..
      .oaaao....oaaao.
      .oaaao....oaaao.
      .oaabo....oaabo.
      ..obo......obo..
      ...o........o...
      ................
      ................
      ................`, { y: '#ffd54f', a: '#26c6da' }, ['y', 'abc']],
    // 팔찌
    'gear:3': [`
      ................
      ................
      ................
      .....oooooo.....
      ...oowaaaawoo...
      ..owwo....owwo..
      .owwo......owwo.
      .owo........owo.
      .owo........owo.
      .oxwo......owxo.
      ..oxwo....owxo..
      ...ooxwwwwxoo...
      .....oooooo.....
      ................
      ................
      ................`, { w: '#cfd8dc', a: '#ab47bc' }, ['wx', 'a']],
    // 별 브로치
    'gear:4': [`
      ................
      .......oo.......
      ......oyyo......
      ......oyyo......
      .....oyyyyo.....
      .ooooyyyyyyoooo.
      .oyyyyyyyyyyyyo.
      ..oyyyyaayyyyo..
      ...oyyyaayyyo...
      ....oyyyyyyo....
      ....oyyyyyyo....
      ...oyyyooyyyo...
      ...oyyo..oyyo...
      ..oyyo....oyyo..
      ..ooo......ooo..
      ................`, { y: '#ffca28', a: '#e53935' }, ['y', 'abc']],
    // 왕관
    'gear:5': [`
      ................
      ................
      ................
      ..o....oo....o..
      .oao..oaao..oao.
      .oyo..oyyo..oyo.
      .oyyooyyyyooyyo.
      .oyyyyyyyyyyyyo.
      .oyyyyyyyyyyyyo.
      .oyyaayyyyaayyo.
      .oyyyyyyyyyyyyo.
      .oooooooooooooo.
      ................
      ................
      ................
      ................`, { y: '#ffd54f', a: '#42a5f5' }, ['y', 'abc']],
    // 부적
    'gear:6': [`
      ................
      .....o....o.....
      ......o..o......
      .......oo.......
      .....oooooo.....
      ...ooyyyyyyoo...
      ..oyyddddddyyo..
      ..oydlldddddyo..
      .oydlldddddddyo.
      .oydddddddddeyo.
      .oyddddddddeeyo.
      ..oydddddeeeyo..
      ..oyyddeeeeyyo..
      ...ooyyyyyyoo...
      .....oooooo.....
      ................`, { y: '#ffd54f', d: '#26a69a' }, ['y', 'del']],
    // 리본
    'gear:7': [`
      ................
      ................
      ................
      .oo..........oo.
      .opoo......oopo.
      .oppqoo..ooqppo.
      .opppqooooqpppo.
      .oppppoaaoppppo.
      .oppppoaaoppppo.
      .opppqooooqpppo.
      .oppqoo..ooqppo.
      .opoo......oopo.
      .oo..........oo.
      ................
      ................
      ................`, { p: '#ec407a', a: '#d81b60' }, ['pqr', 'abc']],
    // 메달
    'gear:8': [`
      ................
      ...oooo..oooo...
      ...oppo..owwo...
      ....oppoowwo....
      .....oppwwo.....
      ......oooo......
      .....oyyyyo.....
      ....oyyyyyyo....
      ...oyyyaayyyo...
      ...oyyaaaayyo...
      ...oyyyaayyyo...
      ...oyyyyyyyyo...
      ....oyyyyyyo....
      .....oooooo.....
      ................
      ................`, { p: '#e53935', w: '#1e88e5', y: '#ffd54f', a: '#f9a825' }, ['p', 'w', 'y', 'a']],
    // 하트
    'gear:9': [`
      ................
      ................
      ..oooo....oooo..
      .oaccao..oaaaao.
      oaccaaaooaaaaabo
      oacaaaaaaaaaaabo
      oaaaaaaaaaaaaabo
      .oaaaaaaaaaaabo.
      ..oaaaaaaaaabo..
      ...oaaaaaaabo...
      ....oaaaaabo....
      .....oaaabo.....
      ......oabo......
      .......oo.......
      ................
      ................`, { a: '#e53935' }, ['abc']],
    'item:box': [`
      ................
      ................
      ................
      ...oooooooooo...
      ..ozzzzzzzzzzo..
      ..oyzzzzzzzzyo..
      ..ozzzzzzzzzzo..
      ..oyyyyyyyyyyo..
      ..ozzzzoyozzzo..
      ..ozzzzoooozzo..
      ..ozzzzzzzzzzo..
      ..oyzzzzzzzzyo..
      ..oooooooooooo..
      ................
      ................
      ................`, { z: '#a0662f', y: '#ffd54f' }, ['zy']],
    'item:relic': [`
      ................
      ................
      .....oooooo.....
      ......oaao......
      .....oaaaao.....
      ...oaaaaaaaao...
      ..oaffaffaffao..
      ..oaaaaaaaaabo..
      ..oafaafaafabo..
      ..oaaaaaaaaabo..
      ...oaaaaaaabo...
      ....oaaaaabo....
      .....oooooo.....
      ....oaaaaaao....
      ....oooooooo....
      ................`, { a: '#4db6ac', f: '#ffd54f' }, ['abf']],
    'item:ticket': [`
      ................
      ................
      ...oooooooooo...
      ...ozzzzzzzzo...
      ....owwwwwwo....
      ....owyyyywo....
      .....owyywo.....
      ......owwo......
      ......owwo......
      .....owwywo.....
      ....owyyyywo....
      ....owyyyywo....
      ...ozzzzzzzzo...
      ...oooooooooo...
      ................
      ................`, { z: '#8d6e63', w: '#e3f2fd', y: '#ffca28' }, ['z', 'wy']],
  };
  const SEED_COLORS = ['#bdbdbd', '#81c784', '#64b5f6', '#ffb74d'];
  const COIN = rows(`
    ................
    ................
    .....oooooo.....
    ...ooaaaaaaoo...
    ..oaacaaaaaabo..
    ..oacaaaaaaabo..
    .oacaaaaaaaabbo.
    .oaaaaaaaaaabbo.
    .oaaaaaaaaaabbo.
    .oaaaaaaaaaabbo.
    .oaaaaaaaaabbbo.
    ..oaaaaaaabbbo..
    ..obaaaaabbbbo..
    ...oobbbbbboo...
    .....oooooo.....
    ................`);
  const GLYPH = {
    N: ['l...l', 'll..l', 'l.l.l', 'l..ll', 'l...l'],
    S: ['.llll', 'l....', '.lll.', '....l', 'llll.'],
    A: ['.lll.', 'l...l', 'lllll', 'l...l', 'l...l'],
    W: ['l...l', 'l...l', 'lllll', 'l.l.l', '.l.l.'],
  };
  const CURRENCY = { np: ['N', '#26a69a'], sp: ['S', '#7cb342'], ap: ['A', '#9575cd'], money: ['W', '#ffc107'] };
  const STEM = rows(`
    ..oo...oo...oo..
    .oddo.odeo.oddo.
    .odddoodeoodddo.
    ..oeddodeoddeo..
    ...oeedddeeeo...
    ....ooddeeoo....
    .....oxxxxo.....
    ................`);

  // ── 정의 ──
  /** 이름 → { w, h, layers: [{ rows, pal, groups, x, y }] } */
  function def(name) {
    const [kind, id] = name.split(':');
    const one = (r, pal, groups) => ({ w: r[0].length, h: r.length, layers: [{ rows: r, pal: { o: OUT, ...pal }, groups, x: 0, y: 0 }] });
    const cropLayer = (cid, y) => {
      const [t, pal] = CROP_ART[cid];
      return { rows: CROP_T[t], pal: { o: OUT, ...pal }, groups: CROP_GROUPS[t] || CROP_GROUPS.default, hintK: CROP_HINT_K[t] || 1, x: 0, y };
    };
    if (kind === 'crop') return { w: 16, h: 16, layers: [cropLayer(id, 0)] };
    if (kind === 'ready') {
      return { w: 16, h: 20, layers: [{ rows: STEM, pal: { o: OUT, d: '#5aae45', x: '#5a3516' }, groups: ['de'], x: 0, y: 12 }, cropLayer(id, 0)] };
    }
    if (kind === 'dish') { const [t, pal] = dishArt(D.DISH_BY_ID[id]); return one(DISH_T[t], pal, DISH_GROUPS); }
    if (kind === 'seed') { const [m, pal, g] = MISC.seed; return one(rows(m), { ...pal, a: SEED_COLORS[id] }, g); }
    if (kind === 'cur') {
      const [g, color] = CURRENCY[id];
      return { w: 16, h: 16, layers: [
        { rows: COIN, pal: { o: OUT, a: color }, groups: ['abc'], x: 0, y: 0 },
        { rows: GLYPH[g], pal: { l: mix(color, -0.6) }, groups: [], x: 6, y: 7 },
        { rows: GLYPH[g], pal: { l: lerp(color, LIGHT_HUE, 0.75) }, groups: [], x: 5, y: 6 },
      ] };
    }
    const m = MISC[name];
    return m ? one(rows(m[0]), m[1], m[2]) : null;
  }

  // ── 음영 ──
  /**
   * 한 층의 픽셀 색. 그룹마다: 가장자리까지 거리 → 볼록한 높이 → 기울기(법선) → 왼쪽 위 빛 → 7단계 중 하나.
   * 힌트 글자(b · c · e …)는 바탕 글자의 단계에서 한 칸 어둡게/밝게. 그룹 밖 글자는 팔레트 색 그대로.
   */
  function shadeLayer(L) {
    const h = L.rows.length, w = L.rows[0].length;
    const at = (x, y) => (x < 0 || y < 0 || x >= w || y >= h ? '.' : L.rows[y][x]);
    const out = Array.from({ length: h }, (_, y) => Array.from({ length: w }, (_, x) => {
      const ch = at(x, y);
      return ch === '.' ? null : L.pal[ch] || null;
    }));
    const darkest = Array.from({ length: h }, () => Array(w).fill(null));
    const LX = -0.5, LY = -0.68, LZ = 0.54;
    const ln = Math.hypot(LX, LY, LZ);
    for (const group of L.groups) {
      const inG = (x, y) => group.includes(at(x, y));
      const cells = [];
      for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) if (inG(x, y)) cells.push([x, y]);
      if (!cells.length) continue;
      const outside = [];
      for (let y = -1; y <= h; y++) for (let x = -1; x <= w; x++) if (!inG(x, y)) outside.push([x, y]);
      const dist = {};
      let R = 0;
      for (const [x, y] of cells) {
        let d = Infinity;
        for (const [ox, oy] of outside) { const v = (x - ox) ** 2 + (y - oy) ** 2; if (v < d) d = v; }
        d = Math.sqrt(d) - 0.5;
        dist[x + ',' + y] = d;
        if (d > R) R = d;
      }
      // 원 단면 높이: 가장자리 0 → 가운데 1
      const H = (x, y) => { const d = dist[x + ',' + y]; return d == null ? 0 : Math.sqrt(Math.max(0, R * R - (R - d) ** 2)) / R; };
      for (const [x, y] of cells) {
        const ch = at(x, y);
        let base = ch, off = 0;
        if (HINT[ch] && group.includes(HINT[ch][0])) { base = HINT[ch][0]; off = HINT[ch][1] * (L.hintK || 1); }
        const color = L.pal[base] || L.pal[ch];
        const nx = -(H(x + 1, y) - H(x - 1, y)) * 1.6, ny = -(H(x, y + 1) - H(x, y - 1)) * 1.6, nz = 1;
        const nl = Math.hypot(nx, ny, nz);
        const diffuse = Math.max(0, (nx * LX + ny * LY + nz * LZ) / (nl * ln));
        let v = 0.3 + 0.7 * diffuse;
        if (diffuse > 0.93) v += 0.08; // 반짝
        // 단계 사이는 2×2 체크무늬로 섞어 부드럽게 (디더링)
        const f = v * (RAMP - 1) - 1 + off;
        const idx = Math.max(0, Math.min(RAMP - 1, Math.floor(f) + (f - Math.floor(f) > DITHER[(y % 2) * 2 + (x % 2)] ? 1 : 0)));
        const rp = ramp(color);
        out[y][x] = rp[idx];
        darkest[y][x] = rp[0];
      }
    }
    // 외곽선: 맞닿은 재질의 가장 어두운 색과 섞는다
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
      if (at(x, y) !== 'o' || !L.pal.o) continue;
      const nb = [[1, 0], [-1, 0], [0, 1], [0, -1]].map(([dx, dy]) => darkest[y + dy]?.[x + dx]).find(Boolean);
      if (nb) out[y][x] = lerp(nb, L.pal.o, 0.45);
    }
    return out;
  }
  /** 이름 → { w, h, px: 줄마다 색 배열 (null = 투명) } */
  function pixels(name) {
    const d = def(name);
    if (!d) return null;
    const px = Array.from({ length: d.h }, () => Array(d.w).fill(null));
    for (const L of d.layers) {
      shadeLayer(L).forEach((row, y) => row.forEach((c, x) => { if (c) px[L.y + y][L.x + x] = c; }));
    }
    return { w: d.w, h: d.h, px };
  }
  function names() {
    return [
      ...Object.keys(MISC).filter((n) => n !== 'seed'),
      ...[0, 1, 2, 3].map((t) => 'seed:' + t),
      ...Object.keys(CURRENCY).map((c) => 'cur:' + c),
      ...D.CROPS.map((c) => 'crop:' + c.id),
      ...D.CROPS.map((c) => 'ready:' + c.id),
      ...D.DISHES.map((d) => 'dish:' + d.id),
    ];
  }
  const cache = {};
  /** 이름 → PNG dataURL (한 번 그린 건 캐시) */
  function url(name) {
    if (name in cache) return cache[name];
    const p = pixels(name);
    if (!p) return (cache[name] = '');
    const cv = document.createElement('canvas');
    cv.width = p.w;
    cv.height = p.h;
    const g = cv.getContext('2d');
    p.px.forEach((row, y) => row.forEach((c, x) => {
      if (!c) return;
      g.fillStyle = c;
      g.fillRect(x, y, 1, 1);
    }));
    return (cache[name] = cv.toDataURL('image/png'));
  }
  /** <img class="px"> — 크기는 CSS로 (정수 배로 키워야 또렷하다) */
  function img(name, alt = '') {
    const el = document.createElement('img');
    el.className = 'px';
    el.src = url(name);
    el.alt = alt;
    el.draggable = false;
    return el;
  }

  F.sprites = { TIER_COLORS, CROP_ART, names, def, pixels, url, img, ramp, dishTemplate: (dish) => dishArt(dish)[0] };
})();
